name: "Push to Feature Branch"
permissions:
  id-token: write
  contents: read
  issues: write
on:
  workflow_dispatch:
  push:
    branches:
      - '*'
      - '!develop'
      - '!stage'
      - '!main'
    
  pull_request:
    branches:
      - main
  
  #
  # pull_request_review:
  #   types: [submitted]

jobs:
  validate-build:
    uses: ./.github/workflows/terraform_plan.yml
    with:
      path: files/accounts/datascience/environments/eu-west-2/wise
      gh_environment: infra-test
    secrets:
      aws_role_to_assume: ${{ secrets.AWS_GITHUB_ACTION_ROLE }}
      aws_default_region: eu-west-2
      terraform_version: ${{ secrets.TERRAFORM_VERSION }}
      personal_access_token:
        ${{ secrets.LN_PAT }}
        #${{ secrets.JN_PAT }}
