name: "Build_TF_Plan"
permissions:
  id-token: write
  contents: read
  issues: write
on:
  workflow_call:
    inputs:
      path:
        description: "Specifies the path of the root terraform module."
        required: true
        type: string
      gh_environment:
        description: "Specifies the GitHub deployment environment."
        required: true
        type: string
    secrets:
      aws_role_to_assume:
        description: "Specifies the AWS_GITHUB_ACTION_ROLE."
        required: true
      aws_default_region:
        description: "Specifies the AWS_DEFAULT_REGION."
        required: true
      terraform_version:
        description: "Specifies the TERRAFORM_VERSION."
        required: true
      personal_access_token:
        description: "Specifies the PERSONAl ACCESS TOKEN"
        required: true

jobs:
  build-plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.path }}
    
    # strategy:
    #   matrix:
    #     environment: [dev, stage, prod]

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.aws_role_to_assume }}
          aws-region: ${{ secrets.aws_default_region }}

      # Terraform checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.personal_access_token }}
          fetch-depth: 0
          #ref: ${{ github.head_ref }}

      # Install the selected version of Terraform CLI 
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ secrets.terraform_version }}

      - name: Terraform Init
        id: init
        run: terraform init -get=true -input=false -reconfigure

      # Run a terraform fmt to check syntax
      - name: Terraform Format
        id: fmt
        run: terraform fmt -recursive -check -diff

      # Run a terraform validate
      - name: Terraform Validate
        id: validate
        if: success() || failure()
        run: terraform validate

      # Run a terraform plan
      - name: Terraform Plan
        id: plan
        run: terraform plan -lock=false -refresh=true
